### ISSUE TITLE
Starting misp_db ... error

### ISSUE THREAD

**Issue by 000lucifer000** [MISP/x_old_misp_docker#107]
Hi Installed MISP through docker image 
ERROR I'm facing is 
`root@MISP:~/misp-docker# sudo docker-compose -f docker-compose-nginx.yml up
WARNING: The MYSQL_HOST variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_DATABASE variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_USER variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The MISP_ADMIN_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The MISP_ADMIN_PASSPHRASE variable is not set. Defaulting to a blank string.
WARNING: The MISP_BASEURL variable is not set. Defaulting to a blank string.
WARNING: The POSTFIX_RELAY_HOST variable is not set. Defaulting to a blank string.
WARNING: The TIMEZONE variable is not set. Defaulting to a blank string.
WARNING: The DATA_DIR variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
Starting misp_web ...
Starting misp_web
Starting misp_db ...
misp_proxy is up-to-date
Starting misp_web ... error

Starting misp_db ... error

**ERROR: for misp_db  Cannot start service db: error while creating mount source path '/db': mkdir /db: read-only file system

ERROR: for web  Cannot start service web: error while creating mount source path '/web': mkdir /web: read-only file system

ERROR: for db  Cannot start service db: error while creating mount source path '/db': mkdir /db: read-only file system
ERROR: Encountered errors while bringing up the project.**
root@MISP:~/misp-docker#
`
Kindly help me make MISP run successfully 
![misp error](https://user-images.githubusercontent.com/47481243/105838963-d4b29900-5ff6-11eb-99e3-d680fbd142e9.PNG)

**Comment by talltechy** [comment]
1. modify the template.env file with your custom variables
2. SAVE AS ".env" in the same directory as template.env, this is what they referred to as the root directory in README.md, the whole file name should just be .env
3. compose

**Comment by 000lucifer000** [comment]
@talltechy i will follow the same and let you know ... Thanks in advance .
