### ISSUE TITLE
Specify Version of misp to download in the Noob installer?

### ISSUE THREAD

**Issue by guirkgumbo** [MISP/x_old_misp_docker#121]
Is there a recommended approach for the downloading a specific version/tag of the misp repo rather than latest of master during the build process?

I tried the to change the git cloned version in the noob_installer.sh but get a sha1 error if I change the file

sha1: a49d5521f405d20fc3dea76ee995e067d01c5c2c does not match the installer sum of: 64d5b38a1d894f6171d3cfc83ba020be461fbecb

**Comment by narly-david** [comment]
I'm definitely interested in this as well!

**Comment by stevengoossensB** [comment]
You would have to regenerate the NODB_INSTALL.sh script, which can be done by modifying the MD files (https://github.com/MISP/MISP/tree/2.4/INSTALL).

A more hacky way to fix your specific issue would be to change the script and regenerate the hashes, so the hash will match. As explained in https://github.com/MISP/misp-docker/issues/122 a more permanent solution would need to be created for this.
