### ISSUE TITLE
misp.local path doesn't work

### ISSUE THREAD

**Issue by Panagiss** [MISP/x_old_misp_docker#127]
```misp.local``` url path for Misp won't work even though the .crt file has the same CN. I can only acces the misp server with ```localhost```. 

I'm new in Misp and i found the docker image that is really handy.
What i tried at first was to find the .crt file in order to pass to curl --cacert option in order to access the api. But it states of course that the .crt file is signed for ```misp.local ``` path. When i hit the path i cannot reach Misp, while ```localhost``` works just fine.

i must be missing something here...

**Comment by stevengoossensB** [comment]
If you want https://misp.local to work, you'll need to add a DNS record for that in your environment. 

Better is to change the hostname directly and to generate a certificate for that new hostname. The initial certificate is just there to have HTTPs work, but it will always be non-sufficient for production usage, as it's a self signed certificate.

**Comment by Panagiss** [comment]
Yeah is what i did thanks for the reply.
