### ISSUE TITLE
misp_web waiting to database to be ready....

### ISSUE THREAD

**Issue by Panagiss** [MISP/x_old_misp_docker#128]
I just used another network rather than the default and now im stuck while the ```misp_web``` is waiting infinitely for the database to be ready. Here is a screenshot:
![image](https://user-images.githubusercontent.com/56695201/128639768-02b4a78d-20dd-4596-889d-bab371567fed.png)

Also just to note that on my .env file i have set ```MYSQL_HOST=misp_web``` and also i tried to ping the ```misp_db``` **from** ```misp_web``` and i succeeded. 

Any suggestions?

**Comment by pietrogu** [comment]
Hi @Panagiss. how did you solve this?

**Comment by jsnblind43** [comment]
Hello,
did you find a solution? currently stuck on the same issue

**Comment by jsnblind43** [comment]
so I solved my problem and I had wrong MYSQL_HOST in web container, as I had to reflect the same MYSQL_HOST in .env and docker-compose.yml
