### ISSUE TITLE
Issue with MISP URL

### ISSUE THREAD

**Issue by withjigs** [MISP/x_old_misp_docker#130]
I have just deployed misp-docker on 2 separate systems and having weird issue with the URL on both. Here is what I see:

**Initial URL.** it works
https://misp-podman.example.com/

Going to **List Events** changes to URL to below, which fails
https://misp-podman.example.com/misp-podman.example.com/events/index

Again going to **List Galaxies** changes the URL to below:
https://misp-podman.example.com/misp-podman.example.com/events/misp-podman.example.com/galaxies/index

One solutions I have found is commenting out 'baseurl' in _/var/www/MISP/app/Config/config.php_ but that does not give me confidence that everything is OK. 

- If I manually type the correct URL (e.g. https://misp-podman.example.com/events/index) the page loads. 

Appreciate any help.

**Comment by QuentCov** [comment]
Running into the same issue. Your solution works, but I also think it feels like a temporary fix. Have you run into any other issues with your current solution?

**Comment by felipefuller** [comment]
I had the same issue! I resolved by defining manually the base url of the MISP server. For this I entered to the container and used the following command:

`sudo -u www-data /var/www/MISP/app/Console/cake Baseurl https://localhost/`

Hope that this works for you!

**Comment by jw4949** [comment]
same here

**Comment by ftoppi** [comment]
Hello,
you need to set the protocol in MISP_BASEURL variable in your .env file:

```
MISP_BASEURL=https://misp-podman.example.com
```

**Comment by stwater20** [comment]
Hi, I tried one way and it turned out very good.

I entered to the container:
`docker exec -it {misp-container} /bin/bash`
then used the following command:
`sudo -u www-data /var/www/MISP/app/Console/cake admin setSetting MISP.baseurl https://localhost/`
