### ISSUE TITLE
fatal: destination path '/var/www/MISP/app/files/scripts/python-cybox' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by ServSlack** [MISP/x_old_misp_docker#133]
I have tried install MISP with Docker in Ubuntu 20.04 and Rocky Linux 8.4, but the script always stop in the same step.

@adulau @xme or another contributtor can help us ?

Entering 'misp-vagrant'
created virtual environment CPython3.8.10.final.0-64 in 472ms
  creator CPython3Posix(dest=/var/www/MISP/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/tmp/tmptmj9gwtl/seed-app-data/v1.0.1.debian.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
fatal: destination path '/var/www/MISP/app/files/scripts/python-cybox' already exists and is not an empty directory.
fatal: destination path '/var/www/MISP/app/files/scripts/python-cybox' already exists and is not an empty directory.
fatal: destination path '/var/www/MISP/app/files/scripts/python-cybox' already exists and is not an empty directory.

![Misp-Docker-Error](https://user-images.githubusercontent.com/32932095/137001352-ffaab50b-37ce-46ca-9e30-3843c467adbc.PNG)
:

**Comment by righel** [comment]
Hello @ServSlack
I just pushed a fix to master, let me know if it solved your issue.
