### ISSUE TITLE
How to properly initialize MySQL DB

### ISSUE THREAD

**Issue by pietrogu** [MISP/x_old_misp_docker#145]
Hi,

when i run docker-compose, misp-web does not go up because it is "waiting for database to be ready"

This let me think that the inizialization of mysql db didn't happen.

Maybe in the guide there is some missing step?

**Comment by pietrogu** [comment]
Error was in MYSQL_HOST variable (setted in wrong way)

**Comment by jsnblind43** [comment]
> Error was in MYSQL_HOST variable (setted in wrong way)

I had the same issue, thank you for hint!
