### ISSUE TITLE
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c bash INSTALL_NODB.sh -A -u]: exit code: 2

### ISSUE THREAD

**Issue by sixfingerfreddy** [MISP/x_old_misp_docker#147]
Windows: docker-compose build
I got TIMEZONE=UTC  in the .env file, which I thought was the issue... but no luck.

 => ERROR [11/19] RUN bash INSTALL_NODB.sh -A -u                                                                                                                 0.9s
------
 > [11/19] RUN bash INSTALL_NODB.sh -A -u:
#15 0.308 INSTALL_NODB.sh: line 73: syntax error near unexpected token `$'{\r''
'15 0.308 INSTALL_NODB.sh: line 73: `MISPvars () {
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c bash INSTALL_NODB.sh -A -u]: exit code: 2
[+] Running 0/1 docker compose up
 - web Error

**Comment by SlightOmission** [comment]
Edit files with an editor that doesn't add carriage returns and line feeds but rather just line feeds.  Something like notepad++ would do it.
