### ISSUE TITLE
Recently released Ubuntu 22.04 LTS breaks installation

### ISSUE THREAD

**Issue by 3c7** [MISP/x_old_misp_docker#149]
As the Dockerfile uses `ubuntu:latest` and the install script is not compatible with 22.04, the build process breaks this way. Also, the installation procedure seems not to be trivially to adapt to 22.04. Until an updated install script is available, it's probably useful to use `ubuntu:focal` (or another working Ubuntu version).

**Comment by righel** [comment]
Hello,
Thanks for the report, as you recommended switched it to `ubuntu:focal` via 673fdc73a32e0c75acbd57b1d6ed9d8c1d517139 until we make it work on `22.04`
