### ISSUE TITLE
cannot build under CentOS7

### ISSUE THREAD

**Issue by jhaar** [MISP/x_old_misp_docker#15]

**Comment by jhaar** [comment]
Hi there, I'm trying to install MISP via misp-docker on a fully patched CentOS7 system, and when I run "docker-compose build", it churns away for a while building stuff and then errors with the below error.

I'm not that skilled with docker, so am not sure how to fix this. Any ideas? Thanks

Step 32/129 : RUN git clone https://github.com/STIXProject/python-stix.git
 ---> Using cache
 ---> 685727774d86
Step 33/129 : WORKDIR /var/www/MISP/app/files/scripts/python-cybox
 ---> Using cache
 ---> 52dec640f77e
Step 34/129 : RUN git checkout v2.1.0.12
 ---> Using cache
 ---> 99602f7daaf7
Step 35/129 : USER root
 ---> Using cache
 ---> bddc54558f3d
Step 36/129 : RUN python setup.py install
 ---> Running in c2e95953f101

running install
running bdist_egg
running egg_info
creating cybox.egg-info
writing requirements to cybox.egg-info/requires.txt
writing cybox.egg-info/PKG-INFO
writing top-level names to cybox.egg-info/top_level.txt
writing dependency_links to cybox.egg-info/dependency_links.txt
writing manifest file 'cybox.egg-info/SOURCES.txt'
reading manifest file 'cybox.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.pyc' found under directory 'examples'
warning: no previously-included files matching '*.pyo' found under directory 'examples'
writing manifest file 'cybox.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
error: can't copy 'cybox/compat.py': doesn't exist or not a regular file
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/cybox
copying cybox/__init__.py -> build/lib.linux-x86_64-2.7/cybox
ERROR: Service 'web' failed to build: The command '/bin/sh -c python setup.py install' returned a non-zero code: 1

**Comment by xx-zhang** [comment]
I runed the same error with you and i install `python-dev python3-dev openssl openssl-dev libssl` and so on but no use , i can't solve it at now . and i have give it up , also i have tried a lot of dockerfile version also raise the same error. i' now built it in ubuntu:18.04 . if run i'll then tell you.

**Comment by xx-zhang** [comment]
> I runed the same error with you and i install `python-dev python3-dev openssl openssl-dev libssl` and so on but no use , i can't solve it at now . and i have give it up , also i have tried a lot of dockerfile version also raise the same error. i' now built it in ubuntu:18.04 . if run i'll then tell you.

it‘s very luck to tell you that it will not build also in ubuntu18.04 , and raised the same error .


```
Installed /usr/local/lib/python2.7/dist-packages/cybox-2.1.0.12-py2.7.egg
Processing dependencies for cybox==2.1.0.12
Searching for python-dateutil
Reading https://pypi.python.org/simple/python-dateutil/
Best match: python-dateutil 2.8.0
Downloading https://files.pythonhosted.org/packages/ad/99/5b2e99737edeb28c71bcbec5b5dda19d0d9ef3ca3e92e3e925e7c0bb364c/python-dateutil-2.8.0.tar.gz#sha256=c89805f6f4d64db21ed966fda138f8a5ed7a4fdbc1a8ee329ce1b74e3c74da9e
Processing python-dateutil-2.8.0.tar.gz
Writing /tmp/easy_install-WbNXfr/python-dateutil-2.8.0/setup.cfg
Running python-dateutil-2.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-WbNXfr/python-dateutil-2.8.0/egg-dist-tmp-8GYtdN
/tmp/easy_install-WbNXfr/python-dateutil-2.8.0/setup.py:20: UserWarning: python_requires requires setuptools version > 24.3
  UserWarning)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
Moving python_dateutil-2.8.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding python-dateutil 2.8.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/python_dateutil-2.8.0-py2.7.egg
Searching for lxml>=2.2.3
Reading https://pypi.python.org/simple/lxml/
Best match: lxml 4.3.3
Downloading https://files.pythonhosted.org/packages/7d/29/174d70f303016c58bd790c6c86e6e86a9d18239fac314d55a9b7be501943/lxml-4.3.3.tar.gz#sha256=4a03dd682f8e35a10234904e0b9508d705ff98cf962c5851ed052e9340df3d90
Processing lxml-4.3.3.tar.gz
Writing /tmp/easy_install-KRFS8b/lxml-4.3.3/setup.cfg
Running lxml-4.3.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-KRFS8b/lxml-4.3.3/egg-dist-tmp-2P9Yps
x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
/tmp/easy_install-KRFS8b/lxml-4.3.3/temp/xmlXPathInit1yJj1R.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
 main (int argc, char **argv) {
 ^
Building lxml version 4.3.3.
Building without Cython.
Using build configuration of libxslt 1.1.28
Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 4
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
ERROR: Service 'web' failed to build: The command '/bin/sh -c python setup.py install' returned a non-zero code: 1
```

## ENV
```
root@vultr:~/misp-docker# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
root@vultr:~/misp-docker# 

root@vultr:~/misp-docker# docker version 
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
root@vultr:~/misp-docker# 
```

**Comment by SteveClement** [comment]
Tested working under CentOS 7 Linux misp-vm.local 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
