### ISSUE TITLE
"docker-compose up" misp_web error

### ISSUE THREAD

**Issue by ghost** [MISP/x_old_misp_docker#154]
Hi there,

I am having issues starting the docker service for MISP. Please see below for the error message.

```
root ➜ /misp-docker (master ✗) $ docker-compose up                                                                     
Removing misp_web
misp_db is up-to-date 

Recreating c483a4264978_misp_web ... error 
ERROR: for c483a4264978_misp_web  Cannot start service web: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "wait-for-it.sh": executable file not found in $PATH: unknown

ERROR: for web  Cannot start service web: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "wait-for-it.sh": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.
```

![Screenshot 2022-07-17 010222](https://user-images.githubusercontent.com/109426929/179360413-f2de0d88-6837-4b72-bf98-626a464c63cc.png)

Can someone please advise and help me? 

Thanks for your time.

**Comment by righel** [comment]
Could you do a `git pull` and try again? somehow seems you are missing [this file](https://github.com/MISP/misp-docker/blob/master/web/wait-for-it.sh)
Then try `docker-compose up --build`

Let me know if that helps.
