### ISSUE TITLE
No such image: misp:latest

### ISSUE THREAD

**Issue by xfaith** [MISP/x_old_misp_docker#156]
Trying to run the misp-docker through portainer and I get the above issue.     Not sure what information would be good to provide

**Comment by w-kramer** [comment]
You have to build the container by yourself. There is no (known to me) official misp docker image available.
Ross Bevington from Microsoft created a blog on how to do that: https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/integrating-open-source-threat-feeds-with-misp-and-sentinel/ba-p/1350371

**Comment by righel** [comment]
Thanks @cult-x, exactly that.
