### ISSUE TITLE
PEAR Server has been down.

### ISSUE THREAD

**Issue by pingeplin** [MISP/x_old_misp_docker#16]
Hi,
Error message exists in line 98, 99 because pear.php.net has been down; therefore, packages can't be downloaded.

User who want to try to use misp-docker are suggest to 
1. Download source code of "Crypt_GPG" and "Net_GeoIP" from GitHub
2. Modify the Dockerfile in ./web to build those packages using ```$ pear package```.

**Comment by SteveClement** [comment]
fixed
