### ISSUE TITLE
Accessing web Interface from remote host

### ISSUE THREAD

**Issue by 0x414C4D** [MISP/x_old_misp_docker#165]
Hi, I've installed my MISP instance following the readme instruction. The installation finished without errors and all seems work. 
Now I need to access the instance in order to configure feeds etc. I can't access from localhost since is a centos sever. And I don't have any other machine on that local network.
 
So I need to access from remote. When put my public ip in the browser I get only the html content. like in the screenshot below.
<img width="943" alt="Screenshot 2023-04-03 114342" src="https://user-images.githubusercontent.com/41760881/229473516-03f4104b-0b55-4448-8099-6af6d2b61b11.png">

How can I make my instance accessible from remote?

**Comment by righel** [comment]
Try accessing via https css/images may not be loading because of the browsers content-security-policy

**Comment by 0x414C4D** [comment]
Sorry, there was a typo in my baseurl. Thankyou for the response anyway.
