### ISSUE TITLE
DockerFile error / RUN php composer.phar install

### ISSUE THREAD

**Issue by asottocasa** [MISP/x_old_misp_docker#20]
When i try to build with ```docker-compose -f "misp/docker-compose.yml``` up -d --build", i got an error on step 48 : ```RUN php composer.phar install --ignore-platform-reqs```

```error
Loading composer repositories with package information
Updating dependencies (including require-dev)

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
                                                                                           

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```

I added this code into Dockerfile before using ```php composer.phar```

```Dockerfile
# FIX COMPOSER
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
# END FIX
```

I found this code here : [PHP 7.3 breaks composer with continue/targeting error](https://github.com/composer/composer/issues/7783#issuecomment-469723539)

**Comment by yaleman** [comment]
This worked for me

**Comment by vulnerabivoro** [comment]
> 
> 
> When i try to build with `docker-compose -f "misp/docker-compose.yml` up -d --build", i got an error on step 48 : `RUN php composer.phar install --ignore-platform-reqs`
> 
> ```
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> 
>                                                                                            
>   [ErrorException]                                                                         
>   "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
>                                                                                            
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
> ```
> 
> I added this code into Dockerfile before using `php composer.phar`
> 
> ```dockerfile
> # FIX COMPOSER
> RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
> RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
> RUN php composer-setup.php
> RUN php -r "unlink('composer-setup.php');"
> # END FIX
> ```
> 
> I found this code here : [PHP 7.3 breaks composer with continue/targeting error](https://github.com/composer/composer/issues/7783#issuecomment-469723539)

Fix confirmed.

**Comment by SteveClement** [comment]
fix merged
