### ISSUE TITLE
Build fails at Step 50/147: RUN php -r "if (hash_file('sha384 ...

### ISSUE THREAD

**Issue by apigban** [MISP/x_old_misp_docker#26]
Error:
/bin/sh: 1: Syntax error: Unterminated quoted string
ERROR: Service 'web' failed to build: The command '/bin/sh -c php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9$' returned a non-zero code: 2

FULL docker build output: https://pastebin.com/raw/GqHv8xAL

**Comment by apigban** [comment]
Fixed by adding to the end of the line **');"**

**STEP 50/147:** RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9$');"

**Comment by SteveClement** [comment]
please git pull and try again
