### ISSUE TITLE
Php mysql plugin missing

### ISSUE THREAD

**Issue by nukeu666** [MISP/x_old_misp_docker#30]
I build the image without errors but the following error shows up

`Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
'class' => 'Mysql',
'message' => 'Selected driver is not enabled',
'enabled' => false,
)`

It can be fixed by installing php7.3-mysql and restarting the container
Should this be added in the Dockerfile too or does the script need to be updated?

**Comment by xme** [comment]
Fixed
