### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ariansvirsky** [MISP/x_old_misp_docker#31]
2019-05-20 11:38:38 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,

anyone is familiar with that?

**Comment by nukeu666** [comment]
I provided a solution in https://github.com/MISP/misp-docker/issues/30
Add "RUN apt install php7.3-mysql" in the dockerfile and rebuild image
