### ISSUE TITLE
error in RUN php composer-setup.php

### ISSUE THREAD

**Issue by 0xwataru** [MISP/x_old_misp_docker#32]
execute docker-compose build，the error is：

[image](https://user-images.githubusercontent.com/12377959/58098054-525fb800-7c0b-11e9-9304-d14da6e6a710.png)

**Comment by GelosSnake** [comment]
Having the same, will try fix it manually.

**Comment by SawWinnNaung** [comment]
Change on line 79 in web/Dockerfile
```
 79 # FIX COMPOSER
 80 RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
 81 #RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
 82 #RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink    ('composer-setup.php'); } echo PHP_EOL;"
 83 RUN php composer-setup.php
 84 #RUN php -r "unlink('composer-setup.php');"
 85 # END FIX
```

**Comment by GelosSnake** [comment]
Everytime the installer is changed this error will return.
A better method should be done to fix it. 
https://getcomposer.org/download/ 

This is the new one:
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

**Comment by SteveClement** [comment]
This is fixed with the latest PR
