### ISSUE TITLE
TT

### ISSUE THREAD

**Issue by xx-zhang** [MISP/x_old_misp_docker#33]
> this is a great project, thanks for all the suports of you.

**Comment by GelosSnake** [comment]
It was working for ages and since MISP PHP was changed the docker now breaks.
This is one of the worst comments / Issues I have seen. 
Learn how to support the open-source community and not trash it like you just did. 
You should be ashamed of your self.

**Comment by SteveClement** [comment]
No worries, I am sure @xx-zhang stumbled over some form of linguistic building blocks.
Thanks for the support. Also: it is fixed.
