### ISSUE TITLE
Issue with run.sh replacement of baseurl

### ISSUE THREAD

**Issue by kvql** [MISP/x_old_misp_docker#34]
run.sh doesn't replacing baseurl, as default value is 'http://misp'

Modified the sed command as shown below

Existing Command:
sed -ie "s/'baseurl' => '',/'baseurl' => '$MISP_BASEURL sfd',/" /var/www/MISP/app/Config/config.php

Replacement Command:
sed -ie "s/'baseurl' => '.*',/'baseurl' => '$MISP_BASEURL sfd',/" /var/www/MISP/app/Config/config.php

**Comment by SteveClement** [comment]
fixed in upcoming commit
