### ISSUE TITLE
Build failed due to incorrect hash in web/Dockerfile

### ISSUE THREAD

**Issue by 3v1lb1t** [MISP/x_old_misp_docker#45]
Ran through the build a few times. Found the error to be with the hash of the file. Pulled the compose file down locally and ran a hash of it. Checked the hash against their docs, it matches up. The new hash is a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1

![image](https://user-images.githubusercontent.com/36797011/63395042-a94a6a00-c37f-11e9-96e1-00843702e1c9.png)

Once I corrected the hash in step 51/144, installation completed correctly.

**Comment by 3v1lb1t** [comment]
Here is the old hash that is currently coded in the web/Dockerfile for checking integrity of composer.php

48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5

**Comment by SteveClement** [comment]
Could you please make a PR? Now that you went 95% of the way :wink:

**Comment by SteveClement** [comment]
Forget about it, there is already a PR. Thus fixed.
