### ISSUE TITLE
MISP cannot connect to MySQL database

### ISSUE THREAD

**Issue by mkorycinski** [MISP/x_old_misp_docker#5]
Hi,

When bringing up the suite through `docker-compose up` I am hitting the wall with error message from MISP:

```
│misp-web    | ERROR 1045 (28000): Access denied for user 'misp'@'172.18.0.3' (using password: YES)
```

I've tried privileges flushing as it was when Dockerfile was still available in @xme repo, however I cannot even login to mysql database using:
```
docker exec -ti misp-db mysql -p
```
or:
```
docker exec -ti misp-db mysql -u root -p
```

Did anyone also have such problem?

**Comment by ebeahan** [comment]
I ran into the same issue. You have to make sure you change your `misp` DB account password here as well before building:

https://github.com/MISP/misp-docker/blob/master/misp-db/init-misp-db.sql#L2

**Comment by Miroka96** [comment]
You do not have to modify this file, instead make sure you modify the variables in the docker-compose file BEFORE building the containers

**Comment by pe3zx** [comment]
Make sure there are no volumes left before building:

```sh
$ sudo rm -rf /data/misp/db/
```

**Comment by SteveClement** [comment]
Some of the points mentioned should resolve this issue.

**Comment by Ari-R** [comment]
Im getting this same error as well now after it working fine with default settings in docker-compose.yml.

I then changed the mysql_password & mysql_root_password values to give them secure passwords, aswell as the same value in database.php and I am now getting this same error, "ERROR 1045 (28000): Access denied for user 'misp'@'172.18.2.5' (using password: YES)".

How can I update the password files without getting this error ?
