### ISSUE TITLE
No Dockerfile in the git

### ISSUE THREAD

**Issue by mahesh557** [MISP/x_old_misp_docker#6]
Hi,
Received below error when following instruction in the Readme.md

padisetu@hostname001:~/MISP>  git clone https://github.com/MISP/misp-docker
Cloning into 'misp-docker'...
remote: Counting objects: 88, done.
remote: Total 88 (delta 0), reused 0 (delta 0), pack-reused 88
Unpacking objects: 100% (88/88), done.
padisetu@hostname001:~/MISP> cd misp-docker/
padisetu@hostname001:~/MISP/misp-docker> docker build -t misp .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/padisetu/MISP/misp-docker/Dockerfile: no such file or directory

Can you help with instructions to install this docker image?
Thanks
Uma

**Comment by Miroka96** [comment]
skip this step and start directly with the next docker-compose build command
I assume the instructions are outdated

**Comment by SteveClement** [comment]
This is solved too.
