### ISSUE TITLE
misp-modules REQUIREMENTS Empty

### ISSUE THREAD

**Issue by quinnhat** [MISP/x_old_misp_docker#62]
Line `157` of web/Dockerfile results in an empty `REQUIREMENTS` file.

`RUN cat REQUIREMENTS | sed 's/aiohttp==3.4.4/aiohttp/g' > REQUIREMENTS`

Should be:

`RUN sed -i 's/aiohttp==3.4.4/aiohttp/g' REQUIREMENTS`

Unfortunately it looks like the current `REQUIREMENTS` is broken so this results in a failed build. 

This appears to be resolved in #51

**Comment by quinnhat** [comment]
Just to clarify, there are dependency issues during `pip install` with the non-empty `REQUIREMENTS`

**Comment by challs** [comment]
Thanks for the report. This was removed in #74 and should no longer be a problem.
