### ISSUE TITLE
Initial build failes

### ISSUE THREAD

**Issue by RichieB2B** [MISP/x_old_misp_docker#64]
I just attempted to build version 3e62c9d20b54ce764ce36cc4bcf020216a445186 but it fails step 52:
```
Step 52/147 : RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
 ---> Running in 58a0783ef7ab
Installer corrupt
Removing intermediate container 58a0783ef7ab
 ---> e62f527096d9
Step 53/147 : RUN php composer-setup.php
 ---> Running in 99c652af7faa
Could not open input file: composer-setup.php
ERROR: Service 'web' failed to build: The command '/bin/sh -c php composer-setup.php' returned a non-zero code: 1
```

**Comment by k7leafclover** [comment]
Very similar failure here:
`Step 52/147 : RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
 ---> Using cache
 ---> 89ec712f3595
Step 53/147 : RUN php composer-setup.php
 ---> Running in e2cca4eb6538
Could not open input file: composer-setup.php
ERROR: Service 'web' failed to build: The command '/bin/sh -c php composer-setup.php' returned a non-zero code: 1`

**Comment by marcelosz** [comment]
It is an issue with the composer-setup.php file change and the resulting SHA384 hash. Check https://getcomposer.org/download/ for the new hash.

**Comment by devnull-** [comment]
Hello all,

I created a tiny PR to fix the issue: https://github.com/MISP/MISP/pull/5473

devnull-

**Comment by peasead** [comment]
If any other wayward Internet traveler runs across this issue, here's how to fix it yourself while @devnull- 's PR gets merged:

CentOS/Ubuntu
`sed -i 's/a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1/baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182/g' misp-docker/web/Dockerfile`

macOS
`sed -i.bak 's/a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1/baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182/g' misp-docker/web/Dockerfile`

**Comment by challs** [comment]
This is now fixed in current master. The issue can be closed

**Comment by RichieB2B** [comment]
Great, thanks!
