### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by Miroka96** [MISP/x_old_misp_docker#9]
Hello!

Even though I modified the MISP_ADMIN_PASSPHRASE variable, I was not able to login using the password specified there.

Instead the default credentials were working (taken from this issue: https://github.com/MISP/MISP/issues/2602):
admin@admin.test:admin

This could be connected to the password requirements, which seem very complex to me and make it even hard to change the password after a successful login.

Please add this issue at least to the readme.

BR,
Miroka

**Comment by SteveClement** [comment]
This is certainly resolved.
